# Generated by Django 4.2.6 on 2023-10-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineapedido',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='lineapedido',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
